//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassic.Demo.DatabaseFirst.WebCore
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class EntityContext : DbContext
	{
		public EntityContext() : base(@"metadata = .\Model\EFClassic_Demo_Model.csdl|.\Model\EFClassic_Demo_Model.ssdl|.\Model\EFClassic_Demo_Model.msl;provider=System.Data.SqlClient;provider connection string='; " + EFClassic.Demo.DatabaseFirst.WebCore.Program.ConnectionString + "';")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Customer> Customers { get; set; }
	}
}
